pipeline {
    agent any

    steps {
        stage('Build'){
            steps{
                sh 'npm install'
            }
        }
        stage("Test"){
            steps{
                sh 'npm test'
            }
        }
    }
}