name: Ci pipeline

on: 
    - push 
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Print hello world"
              run: echo "hello world"

            - name: "Print current date"
              run: data

          